// This is a file generated by the yeoman generator hapijs

/**
 * Dao layer which actually gets wolfram from the datastore
 *
 * @type {exports}
 */
var Boom = require('boom');
var wolframAppId = 'QAH7L9-76P28363U4';

/**
 * Get's all wolframs
 *
 * @param callback
 */
exports.calculate = function (callback) {
	
	var wolfram = require('wolfram').createClient(wolframAppId);
	
	wolfram.query("integrate 2x", function(err, result) {
	  if(err) throw err
	  console.log("Result: %j", result)
		callback(null, result);
	});
	
	// TODO: Implement dao method and call callback(null, <data>)
	//return callback(Boom.notImplemented());
};

/* Add new methods above */