// This is a file generated by the yeoman generator hapijs

/**
 * Unit tests for all the wolfram endpoints
 *
 * @type {exports}
 */

var Lab = require('lab');
var server = require('../../');

var lab = exports.lab = Lab.script();

lab.experiment('calculating wolframs', function() {

  lab.test('should be successful', function (done) {
    var options = {
      method: 'GET',
      url: '/wolfram',
      payload: {

      }
    };

    server.inject(options, function (response) {
      var result = response.result;

      Lab.expect(response.statusCode).to.equal(200);

      done();
    });
  });

});

