// This is a file generated by the yeoman generator hapijs

/**
 * Controller which handles requests/responses relating to wolfram
 *
 * @type {wolframDao|exports}
 */
var wolframDao = require('./wolfram-dao');
var Boom = require('boom');

/**
 * Gets all wolframs
 *
 * @param req
 * @param reply
 */
exports.calculate = function (req, reply) {

	wolframDao.calculate(req.params.equation, function (err, data) {
		if (err) {
			return reply(Boom.wrap(err));
		}
		reply(data);
	});
};

/* Add new methods above */
